

spring:
  datasource:
    url : ENC(iScbxuEhpeGFN8iOJ/FQp4Hiz+ANjYy4eX4HfysjH3MnEdt5ZdaC6At7cNIAt1hL290ZdYzlKO2aK/ZUbwNS9NMWHKYS/w4cB/ca/xMfcgvnh0MxGJ0n4avPnxo4OEQXMMZHvu2M9tMt/PVTHNgBbLnoMyZviaVMoEYVrpAoZ/5JK4YUGjUkv6Im+EIQPRb237WV99ts/rba78Cb7zUSijtsgTHbarE4Q8GuURFPM/w=)
    username : ENC(EpONZ6ZLmgNWbOzv1e+h+g==)
    password : ENC(Mvz56tUR267X93Yt+LTgwxdezJQTtbwr)
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
        ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  web:
    resources:
      add-mappings: true
  main:
      allow-bean-definition-overriding: true
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    include:
      - aws
      - credentials
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES
    password: letsson
    pool-size: 1
    property:
      prefix: ENC(
      suffix: )



logging:
  level:
    root: info


server:
  port: ${PORT:8080}











